kind: Deployment
apiVersion: apps/v1
metadata:
  name: kproject
spec:
  replicas: 2
  selector:      # tells the controller which pods to watch/belong to
    matchLabels:
      app: kproject
  template:
    metadata:
      labels:
        app: kproject
    spec:
      containers:
      - name: kprogect
        image: nataliasv/pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
