kind: Deployment
apiVersion: apps/v1
metadata:
  name: k_project
spec:
  replicas: 2
  selector:      # tells the controller which pods to watch/belong to
    matchLabels:
      app: k_project
  template:
    metadata:
      labels:
        app: k_project
    spec:
      containers:
      - name: k_progect
        image: nataliasv/pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
