kind: Service                             
apiVersion: v1
metadata:
  name: kproject
  labels:
    app: kproject
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kproject                    
  type: LoadBalancer                 
