kind: Service                             
apiVersion: v1
metadata:
  name: k_project
  labels:
    app: k_project
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: k_project                    
  type: LoadBalancer                 
